# Generated by Django 5.1 on 2025-06-12 01:14

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_tag_remove_product_category_product_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='banner_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='products/banners/%Y/%m', verbose_name='Баннер'),
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='products/gallery/%Y/%m', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='ALT-текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фотографии товаров',
                'ordering': ['order', 'id'],
            },
        ),
    ]
