# Generated by Django 5.1 on 2025-06-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_photo_product_banner_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner_photo',
            field=models.ImageField(blank=True, upload_to='products/banners/%Y/%m', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to='products/gallery/%Y/%m', verbose_name='Фото'),
        ),
    ]
