# Generated by Django 5.1 on 2025-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_payment_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='ожидание', max_length=50, null=True, verbose_name='Статус платежа'),
        ),
    ]
