# Generated by Django 5.1 on 2025-02-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ожидание', 'Ожидает'), ('оплачен', 'Оплачен'), ('отменен', 'Отменен')], default='ожидание', max_length=50, null=True, verbose_name='Статус платежа'),
        ),
    ]
