# Generated by Django 5.1 on 2025-02-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='free_case_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бесплатных чехлов'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатный товар'),
        ),
    ]
