# Generated by Django 5.1 on 2025-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_order_free_case_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='welcome_discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Welcome-скидка'),
        ),
    ]
